db_file: "bolt.db"

bot_url: "https://t.me/dv0vd_pocket_bot"

messages:
  responses:
    start: "Привет! Чтобы сохранять ссылки в своём Pocket аккаунте, для начала тебе необходимо дать мне на это доступ. Для этого переходи по ссылке:\n%s"
    already_authorized: "Ты уже авторизирован. Присылай ссылку, а я её сохраню"
    saved_successfully: "Ссылка успешно сохранена"
    unknown_command: "Я не знаю такой команды"
  errors:
   default: "Произошла неизвестная ошибка"
   invalid_url: "Это невалидная ссылка!"
   unauthorized: "Ты не авторизирован! Используй команду /start"
   unable_to_save: "Не удалось сохранить ссылку. Попробуй ещё раз позже"